from selenium import webdriver
import time
navegador = webdriver.Edge()
navegador.set_window_size(1920, 1080)
navegador.get('https://login.yahoo.com/account/create?.intl=br&.lang=pt-BR&src=ym&specId=yidregsimplified&activity=header-signup&pspid=1197806870&.done=https%3A%2F%2Fmail.yahoo.com%2Fd%3F.lang%3Dpt-BR%26.intl%3Dbr&done=https%3A%2F%2Fmail.yahoo.com%2Fd%3F.lang%3Dpt-BR%26.intl%3Dbr')
nome = navegador.find_element('css selector', 'input#usernamereg-firstName')
nome.send_keys('Irlan')
sobrenome = navegador.find_element('css selector', 'input#usernamereg-lastName')
sobrenome.send_keys('Ferreira da Silva')
email = navegador.find_element('css selector', 'input.icon-email')
email.send_keys('irlanferreiradasilva2@gmail.com')
senha = navegador.find_element('css selector', 'input.icon-password')
senha.send_keys('Santacruz2023')
ano = navegador.find_element('css selector', 'input.icon-birthday')
ano.send_keys('2000')
ano.submit()
fone = navegador.find_element('css selector', 'input#usernamereg-phone')
fone.send_keys('81984192135')
fone.submit()
time.sleep(30)